### ISSUE TITLE
Debug assertion failure when running in Debug mode.

### ISSUE THREAD

**Issue by arjunptm** [NVlabs/abstract-fps#78] opened 2019-11-11 21:01 UTC
First assertion begins with

```
Debug assertion failure

Expression: m_frame.rotation.isOrthonormal()
e:\thesis\g3d\g3d10\g3d-app.lib\source\entity.cpp:124
```
and leads to a series of assertions such as 
```
Barycentric coords don't match intersection.

Expression: blend.fuzzyEq(outLocation)
e:\thesis\g3d\g3d10\g3d-base.lib\source\collisiondetection.cpp:1677
```

Visual Studio version: VS2017 15.9.17

**Comment by bboudaoud-nv** [comment] 2019-11-12 20:47
I believe this issue has now been resolved. @arjunptm maybe you can pull the latest change and see if the problem is still occurring on your end. If not, feel free to close the issue (or I can for you).

**Comment by bboudaoud-nv** [comment] 2019-11-14 21:51
I'm going to close this issue for now, if it crops back up we can reopen.

**Closed by bboudaoud-nv** 2019-11-14 21:51 UTC
Labels: invalid
