### ISSUE TITLE
Mouse cursor hides on question prompts

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#230] opened 2020-08-11 21:09 UTC
I've had it reported by users, and have noticed myself an intermittent bug where sometimes on transitioning to a question response phase of a session the mouse cursor doesn't show. I can sometimes work around this bug by opening the menu.

I'll attempt to figure out how to reproduce this bug and post the steps soon.

**Comment by jspjutNV** [comment] 2020-08-17 17:46
We're having a hard time reproducing this issue consistently. We may just end up closing the issue until someone can reproduce it.

**Comment by bboudaoud-nv** [comment] 2020-08-17 18:27
This type of error seems to be reproducible (at least in one case) by opening and closing the settings menu while the question dialog is up. This results in the mouse cursor being hidden while the question is still presented.

**Comment by jspjutNV** [comment] 2020-08-19 17:55
Given that this is reproducible, but avoidable with a work around, I'm going to defer this one until the September release.

**Closed** 2020-09-28 13:17 UTC
Labels: bug
