### ISSUE TITLE
Visualization of player health state and change

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#40] opened 2019-07-16 21:36 UTC
Player health state as health bar.
A large, eccentric red ring when player health decreases (receiving hit from enemy).

**Comment by jspjutNV** [comment] 2019-07-17 19:23
I had thought the old HUD was designed to show health and ammo, but it currently seems to show the timer and score (set `showHUD = true` in `experimentConfig.Any` to test it).

Does anyone have a design in mind? If we create a player health bar, that could be placed at the top and shrink as damage is done. 

If we just want text showing the health percentage out of 100%, we could either switch out one of the current timer and score values and draw health there instead. Health in text would be the easier implementation to do, but I'm most worried about getting a design we like.

Are there any game references we'd like to model our design after?

**Comment by bboudaoud-nv** [comment] 2019-07-17 22:16
When I refactored the HUD to get it working I guessed at what many of these parameters were originally intended to display. I will say that I think making player health a readable percent is less intuitive than a bar. I'd like to provide _much_ more HUD configuration in the future, but for now I like the idea of a (sizeable?) health bar option in a corner/top/bottom of the screen and possible a similar weapon status indicator to provide the remaining ammo.

Something like this seems reasonable to me (less the fancy weapon status):
![image](https://user-images.githubusercontent.com/48839018/61415531-ecb44300-a8be-11e9-9083-e7b5639bf6a2.png)

**Comment by bboudaoud-nv** [comment] 2019-07-17 22:17
I think we should also consider adding a damage direction indicator, as is common in many FPS games where damage is dealt from enemies at all angles. Putting this here since its also HUD and health related.

![image](https://user-images.githubusercontent.com/48839018/61415621-33a23880-a8bf-11e9-83fe-d8ef8721e728.png)

**Comment by jspjutNV** [comment] 2019-07-18 14:15
Fortnite puts the player health bar in the bottom center of the screen so it overlaps the player's model somewhat (and has transparency so it doesn't fully block).

Overwatch puts the player health bar in the bottom left corner. Call of Duty and Apex Legends also use the bottom left. Battlefield hates giving the player information so they encode health through a full screen reddish tint that is mostly at the edges of the screen. Most FPS games I could find use the bottom left.

Some other third person games use the top center.

I think we should follow the dominant FPS-style here which would be to place the player health bar in the bottom left corner. The health should be left justified, so you lose health from the right side of the bar first.

While we're talking about HUD elements, I noticed in my survey that ammo counters typically are shown on the bottom right corner in a similar fashion, but using a different color. Health usually goes green to red or somewhere in that space (could be a single color). Ammo tends to use a blue-ish color. Sometimes they're both just white.

Since we already can configure enemy health color changing, I vote for using the same player health gradient. The ammo should definitely be different, so let's just make it either blue or white (whoever implements it can choose). Both bars should have transparency so you can still see the underlying world geometry.

**Comment by bboudaoud-nv** [comment] 2019-07-18 14:30
The position/size of these 2D HUD elements can/should? be configurable via a `.Any` file, this way the experiment developer can set them per their expectations. This may be more difficult for HUD elements with fixed size images, but otherwise I think we should support custom placement of the player HUD elements.

**Comment by bboudaoud-nv** [comment] 2019-07-18 18:21
A basic, configurable player health bar has been added as of [a recent commit](https://github.com/NVlabs/abstract-fps/commit/5805f0a462c3786cef5bb625c1fcbb6bb3de5afc). Closing this for now.

**Closed by bboudaoud-nv** 2019-07-18 18:21 UTC
Labels: enhancement
